version: "3.8"

services:

  online_shop:
    image: sushants1/shopping-app:latest
    ports:
      - "5173:5173"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - online_shop

networks:
  online_shop:
    driver: bridge
